# Generated by Django 2.2.2 on 2019-06-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
